/*
 * Copyright 2017 The RoboZonky Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.robozonky.strategy.natural;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;

import com.github.robozonky.internal.api.Defaults;

/**
 * Used for testing of strategies generated by natural-strategy-setup.
 */
public class GeneratedStrategyVerifier {

    public static ParsedStrategy parseWithAntlr(final String strategy) throws IOException {
        final InputStream strategyStream = new ByteArrayInputStream(strategy.getBytes(Defaults.CHARSET));
        return NaturalLanguageStrategyService.parseWithAntlr(strategyStream);
    }
}
