package com.github.robozonky.strategy.natural;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

/**
 * Used for testing of strategies generated by natural-strategy-setup.
 */
public class GeneratedStrategyVerifier {
    public static ParsedStrategy parseWithAntlr(final String strategy) throws IOException {
        InputStream strategyStream = new ByteArrayInputStream(strategy.getBytes(StandardCharsets.UTF_8.name()));
        return NaturalLanguageStrategyService.parseWithAntlr(strategyStream);
    }
}
