# Uses Github's default JDKs (Azul) to test the release, for simplicity of configs.
name: Acceptance

on: [pull_request]

env:
  DEFAULT_JDK_VERSION: 11
  STABILIZING_PROPERTIES: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
  STREAMLINING_PROPERTIES: -Dassembly.skipAssembly -Denforcer.skip
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  full:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from Github
        uses: actions/checkout@v2
      - name: Set up the JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.DEFAULT_JDK_VERSION }}
      # See https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven#caching-dependencies
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Compile and test all modules, skipping mutation coverage
        run: mvn --batch-mode verify -Dpit.skip=true ${{ env.STABILIZING_PROPERTIES }}
  mutation: # Takes a very long time, run all modules in parallel.
    name: Mutation coverage
    needs: full
    strategy:
      fail-fast: false # Always see all results
      matrix:
        module: [robozonky-api, robozonky-app, robozonky-notifications, robozonky-strategy-natural, robozonky-cli, robozonky-installer]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from Github
        uses: actions/checkout@v2
      - name: Set up the JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.DEFAULT_JDK_VERSION }}
      # See https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven#caching-dependencies
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Compile all modules without testing
        run: mvn --batch-mode clean install -DskipTests ${{ env.STABILIZING_PROPERTIES }}
      - name: Run mutation coverage on a single module
        run: |
          cd ${{ matrix.module }}
          mvn --batch-mode install ${{ env.STABILIZING_PROPERTIES }} ${{ env.STREAMLINING_PROPERTIES }}
  quick:
    name: Cross-platform sanity check
    strategy:
      fail-fast: false # Always see all results on all platforms.
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        jvm: [ 11, 16 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout from Github
        uses: actions/checkout@v2
      - name: Set up the JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jvm }}
      # See https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven#caching-dependencies
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Compile and test all modules, skipping mutation coverage
        run: mvn --batch-mode verify -Dpit.skip=true ${{ env.STABILIZING_PROPERTIES }}
