name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up the JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Compile without testing
      run: mvn --batch-mode clean install dependency:go-offline -DskipTests -Dgpg.skip
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rzModule: [robozonky-api, robozonky-app, robozonky-cli, robozonky-installer, robozonky-notifications, robozonky-strategy-natural]
    steps:
      - uses: actions/checkout@v1
      - name: Set up the JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build required modules
        run:
          mvn --batch-mode -pl ${{ matrix.rzModule }} -am clean install -DskipTests -Denforcer.skip -Dgpg.skip
      - name: Run the test coverage
        run:
          mvn --batch-mode -pl ${{ matrix.rzModule }} install -Dassembly.skipAssembly -Denforcer.skip -Dgpg.skip

