name: RoboZonky CI

on: [push, pull_request]

jobs:
  full:
    name: Full test on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up the JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Compile all modules without testing
      run: mvn --batch-mode clean install dependency:go-offline -Dgpg.skip -DskipTests
    - name: Test all modules
      run: mvn --batch-mode install -Dassembly.skipAssembly -Denforcer.skip -Dgpg.skip -Dpit.skip=true
    - name: Test all modules incl. mutation coverage
      run: mvn --batch-mode install -Dassembly.skipAssembly -Denforcer.skip -Dgpg.skip
  quick:
    name: Quick test on other platforms
    strategy:
      fail-fast: false # Always see all results on all platforms.
      matrix:
          os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up the JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compile and test all modules, skipping mutation coverage
        shell: bash
        run: mvn --batch-mode install -Denforcer.skip -Dgpg.skip -Dpit.skip=true

