name: Release

on: [pull_request]

env:
  JDK_VERSION: 14
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    strategy:
      fail-fast: false # Always see all results on all platforms.
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VERSION }}
      - name: Determine RoboZonky version
        run: |
          ROBOZONKY_VERSION=$(mvn -q \
            -Dexec.executable="echo" \
            -Dexec.args='${project.version}' \
            --non-recursive \
            org.codehaus.mojo:exec-maven-plugin:1.6.0:exec \
          )
          echo "::set-env name=ROBOZONKY_VERSION::$ROBOZONKY_VERSION"
      - name: Check RoboZonky version
        run: echo "The detected RoboZonky version is $ROBOZONKY_VERSION"
      - name: Deploy Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          maven_args: "-DskipTests"
          maven_profiles: release
          maven_goals_phases: deploy
          gpg_private_key: ${{ secrets.MAVEN_CENTRAL_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.MAVEN_CENTRAL_PRIVATE_KEY_PASSWORD }}
          server_id: ossrh
          nexus_username: ${{ secrets.MAVEN_CENTRAL_ACCOUNT_NAME }}
          nexus_password: ${{ secrets.MAVEN_CENTRAL_ACCOUNT_PASSWORD }}
