name: Release

on: [pull_request]

env:
  JDK_VERSION: 14
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OSSRH_USERNAME: ${{ secrets.MAVEN_CENTRAL_ACCOUNT_NAME }}
  OSSRH_PASSWORD: ${{ secrets.MAVEN_CENTRAL_ACCOUNT_PASSWORD }}

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VERSION }}
      - name: Import GPG secrets
        shell: bash
        run: echo "${{ secrets.MAVEN_CENTRAL_PRIVATE_KEY }}" >> secret.gpg
      - name: Compile all modules without testing
        run: mvn --batch-mode clean install dependency:go-offline -Dgpg.skip -DskipTests
      - name: Deploy Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          maven_profiles: release
          gpg_private_key: "secret.gpg"
          gpg_passphrase: ${{ secrets.MAVEN_CENTRAL_PRIVATE_KEY_PASSWORD }}
          nexus_username: ${{ secrets.MAVEN_CENTRAL_ACCOUNT_NAME }}
          nexus_password: ${{ secrets.MAVEN_CENTRAL_ACCOUNT_PASSWORD }}
