name: Release

on: [pull_request]

defaults:
  run:
    shell: bash

env:
  JDK_VERSION: 14
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_project:
    name: Build the initial project
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VERSION }}
      - name: Determine RoboZonky version
        run: |
          ROBOZONKY_VERSION=$(mvn -q \
            -Dexec.executable="echo" \
            -Dexec.args='${project.version}' \
            --non-recursive \
            org.codehaus.mojo:exec-maven-plugin:1.6.0:exec \
          )
          echo "::set-env name=ROBOZONKY_VERSION::$ROBOZONKY_VERSION"
      - name: Check RoboZonky version
        run: echo "The detected RoboZonky version is $ROBOZONKY_VERSION"
      - name: Run the build
        run: mvn clean install -DskipTests
      - name: Share Main JAR for JLink
        uses: actions/upload-artifact@v1
        with:
          name: robozonky-app
          path: robozonky-app/target/robozonky-app-$ROBOZONKY_VERSION-full.jar
      - name: Share CLI JAR for JLink
        uses: actions/upload-artifact@v1
        with:
          name: robozonky-cli
          path: robozonky-cli/target/robozonky-cli-$ROBOZONKY_VERSION-full.jar
  jlink:
    name: JLink the built binaries
    needs: build_project
    strategy:
      fail-fast: false # Always see all results on all platforms.
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download Main JAR for JLink
        uses: actions/download-artifact@v1
        with:
          name: robozonky-app
      - name: Run JLink for the Main JAR
        run:
          .github/workflows/jlink.sh robozonky-app jre
          zip -r robozonky-app-jre.zip jre
      - name: Upload JLinked JRE for Main JAR
        uses: actions/upload-artifact@v1
        with:
          name: robozonky-app-jre.zip
          path: robozonky-app-jre.zip

#jobs:
#  release:
#    name: Release
#    strategy:
#      fail-fast: false # Always see all results on all platforms.
#      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
#    runs-on: ${{ matrix.os }}
#    steps:
#      - name: Deploy Maven package
#        uses: samuelmeuli/action-maven-publish@v1
#        with:
#          maven_args: "-DskipTests"
#          maven_profiles: release
#          maven_goals_phases: deploy
#          gpg_private_key: ${{ secrets.MAVEN_CENTRAL_PRIVATE_KEY }}
#          gpg_passphrase: ${{ secrets.MAVEN_CENTRAL_PRIVATE_KEY_PASSWORD }}
#          server_id: ossrh
#          nexus_username: ${{ secrets.MAVEN_CENTRAL_ACCOUNT_NAME }}
#          nexus_password: ${{ secrets.MAVEN_CENTRAL_ACCOUNT_PASSWORD }}
