name: Release

on: [pull_request]

env:
  JDK_VERSION: 14
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    strategy:
      fail-fast: false # Always see all results on all platforms.
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VERSION }}
      - name: Compile all modules without testing
        run: mvn --batch-mode clean install dependency:go-offline -DskipTests
      - name: Deploy Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          maven_args: "-DskipTests"
          maven_profiles: release
          maven_goals_phases: deploy
          gpg_private_key: ${{ secrets.MAVEN_CENTRAL_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.MAVEN_CENTRAL_PRIVATE_KEY_PASSWORD }}
          server_id: ossrh
          nexus_username: ${{ secrets.MAVEN_CENTRAL_ACCOUNT_NAME }}
          nexus_password: ${{ secrets.MAVEN_CENTRAL_ACCOUNT_PASSWORD }}
