name: Release

on: [pull_request]

env:
  JDK_VERSION: 14
  PRENATIVE_REPO_FILENAME: "robozonky-build-prenative.zip"

defaults:
  run:
    shell: bash

jobs:
  build_project:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VERSION }}
      - name: Run the build
        run: mvn clean install --batch-mode -DskipTests
      - name: Share the build directory # So that all subsequent steps use identical binaries.
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PRENATIVE_REPO_FILENAME }}
          path: '**/*'
  jlink1:
    name: JLink the Main app and CLI binaries
    needs: build_project
    strategy:
      fail-fast: false # Always see all results on all platforms.
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download the build directory
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.PRENATIVE_REPO_FILENAME }}
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VERSION }}
      - name: Determine RoboZonky version
        run: |
          ROBOZONKY_VERSION=$(mvn -q \
            -Dexec.executable="echo" \
            -Dexec.args='${project.version}' \
            --non-recursive \
            org.codehaus.mojo:exec-maven-plugin:1.6.0:exec \
          )
          echo "::set-env name=ROBOZONKY_VERSION::$ROBOZONKY_VERSION"
      - name: Check RoboZonky version
        run: echo "The detected RoboZonky version is $ROBOZONKY_VERSION"
      - name: Run JLink for the Main JAR
        run: |
          .github/workflows/jlink.sh robozonky-app/target/robozonky-app-$ROBOZONKY_VERSION-full.jar ${{ github.workspace }}/app-jre
          zip -r ${{ github.workspace }}/robozonky-app-jre.zip ${{ github.workspace }}/app-jre
      - name: Run JLink for the CLI JAR
        run: |
          .github/workflows/jlink.sh robozonky-cli/target/robozonky-cli-$ROBOZONKY_VERSION-full.jar ${{ github.workspace }}/cli-jre
          zip -r ${{ github.workspace }}/robozonky-cli-jre.zip ${{ github.workspace }}/cli-jre
      - name: Determine OS shorthand # Avoid proliferation of Ubuntu and remove the -latest suffix
        run:
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
          echo "::set-env name=ROBOZONKY_OS::windows"
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          echo "::set-env name=ROBOZONKY_OS::macos"
          else
          echo "::set-env name=ROBOZONKY_OS::linux"
          fi
      - name: Upload JLinked JREs
        uses: actions/upload-artifact@v2
        with:
          name: robozonky-jre-$ROBOZONKY_OS
          path: ${{ github.workspace }}/robozonky-*-jre.zip
  distributions1:
    name: Prepare distribution archives for Main daemon and CLI
    needs: jlink1
    runs-on: ubuntu-latest
    steps:
      - name: Download the build directory
        uses: actions/download-artifact@v2
        with:
          name: robozonky-build.zip
          path: ${{ github.workspace }}/.
      - name: Unzip the build directory
        run:
          unzip ${{ github.workspace }}/${{ env.PRENATIVE_REPO_FILENAME }} .
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VERSION }}
      - name: Download Linux JREs
        uses: actions/download-artifact@v2
        with:
          name: robozonky-jre-linux.zip
          path: robozonky-distributions/robozonky-distributions-full/target/
      - name: Download MacOS JREs
        uses: actions/download-artifact@v2
        with:
          name: robozonky-jre-macos.zip
          path: robozonky-distributions/robozonky-distributions-full/target/
      - name: Download Windows JREs
        uses: actions/download-artifact@v2
        with:
          name: robozonky-jre-windows.zip
          path: robozonky-distributions/robozonky-distributions-full/target/

#jobs:
#  release:
#    name: Release
#    strategy:
#      fail-fast: false # Always see all results on all platforms.
#      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
#    runs-on: ${{ matrix.os }}
#    steps:
#      - name: Deploy Maven package
#        uses: samuelmeuli/action-maven-publish@v1
#        with:
#          maven_args: "-DskipTests"
#          maven_profiles: release
#          maven_goals_phases: deploy
#          gpg_private_key: ${{ secrets.MAVEN_CENTRAL_PRIVATE_KEY }}
#          gpg_passphrase: ${{ secrets.MAVEN_CENTRAL_PRIVATE_KEY_PASSWORD }}
#          server_id: ossrh
#          nexus_username: ${{ secrets.MAVEN_CENTRAL_ACCOUNT_NAME }}
#          nexus_password: ${{ secrets.MAVEN_CENTRAL_ACCOUNT_PASSWORD }}
